M48
; DRILL file {KiCad 8.0.3} date 2024-06-19T16:57:15+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-19T16:57:15+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
%
G90
G05
T1
X6.1417Y-2.8346
T2
X5.6417Y-3.1102
X6.1417Y-3.1102
T3
X4.9606Y-3.0102
X4.9606Y-3.1102
M30
